language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install six
  - pip install flake8
  - pip install jupyter
# command to run tests
script:
- py.test

notifications:
  email: false
