language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install six
  - pip install jupyter
# command to run tests
script:
- py.test

notifications:
  slack: upes-ai:eqI31DE8VCXS86periWJCIhU
